[package]
name = "rosa"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
log4rs = "1.3.0"
num-traits = "0.2.19"
once_cell = "1.21.3"
oneshot = "0.1.11"
rand = "0.9.1"
rand_pcg = "0.9.0"
rayon = "1.10.0"
